"""
FlowScope PDF Exporter (Enhanced Edition).

Renders curated Markdown guides with Cupid Player aesthetic — soft pastels,
chunky borders, retro visual hierarchy, and distinctive component styling.
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

try:
    import markdown
except ImportError:
    markdown = None  # type: ignore

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    HRFlowable,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


# ---------------------------------------------------------------------------
# PDF Canvas
# ---------------------------------------------------------------------------

class FlowScopeCanvas(canvas.Canvas):
    """Enhanced canvas with FlowScope branding, headers, footers,
    and page decoration."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)

        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decoration(num_pages)
            super().showPage()

        super().save()

    def draw_page_decoration(self, page_count: int):
        """Draw FlowScope-branded headers, footers and decoration."""

        self.saveState()

        if self._pageNumber == 1:
            self.setStrokeColor(
                colors.HexColor("#ec4899")
            )
            self.setLineWidth(2.5)
            self.line(36, 772, 576, 772)

        else:
            self.setFont(
                "Helvetica-Bold",
                8,
            )

            self.setFillColor(
                colors.HexColor("#c084fc")
            )

            self.drawString(
                36,
                762,
                "⟡ FlowScope Terminal Guide",
            )

            self.setStrokeColor(
                colors.HexColor("#c084fc")
            )

            self.setLineWidth(1.5)

            self.line(
                36,
                758,
                576,
                758,
            )

        # Footer line
        self.setStrokeColor(
            colors.HexColor("#ddd6fe")
        )

        self.setLineWidth(1.5)

        self.line(
            36,
            48,
            576,
            48,
        )

        # Footer text
        self.setFont(
            "Helvetica",
            8,
        )

        self.setFillColor(
            colors.HexColor("#9370db")
        )

        footer_text = "Generated by FlowScope"
        page_str = f"Page {self._pageNumber} of {page_count}"

        self.drawString(
            36,
            33,
            footer_text,
        )

        self.drawRightString(
            576,
            33,
            page_str,
        )

        # Decorative dots
        self.setFillColor(
            colors.HexColor("#fce7f3")
        )

        for i in range(3):
            x = 300 + (i * 12) - 12

            self.circle(
                x,
                27,
                1.5,
                fill=1,
            )

        self.restoreState()


# ---------------------------------------------------------------------------
# Styles
# ---------------------------------------------------------------------------

def _build_styles() -> dict[str, ParagraphStyle]:
    """Build FlowScope-themed paragraph styles."""

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=28,
        leading=32,
        textColor=colors.HexColor("#6b21a8"),
        spaceAfter=4,
    )

    h1_style = ParagraphStyle(
        "DocH1",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        textColor=colors.HexColor("#7c3aed"),
        spaceBefore=18,
        spaceAfter=2,
        keepWithNext=True,
    )

    h2_style = ParagraphStyle(
        "DocH2",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=15,
        leading=19,
        textColor=colors.HexColor("#c084fc"),
        spaceBefore=16,
        spaceAfter=8,
        keepWithNext=True,
    )

    h3_style = ParagraphStyle(
        "DocH3",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=16,
        textColor=colors.HexColor("#db2777"),
        spaceBefore=12,
        spaceAfter=4,
        keepWithNext=True,
    )

    body_style = ParagraphStyle(
        "DocBody",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=15,
        textColor=colors.HexColor("#4c1d95"),
        spaceAfter=10,
    )

    bullet_style = ParagraphStyle(
        "DocBullet",
        parent=body_style,
        leftIndent=18,
        firstLineIndent=-12,
        spaceAfter=6,
    )

    # -----------------------------------------------------------------------
    # FIX:
    #
    # Code text now uses Paragraph instead of Preformatted.
    #
    # Paragraph automatically wraps long lines, which prevents PowerShell
    # errors and other long terminal output from escaping the code box.
    # -----------------------------------------------------------------------

    code_style = ParagraphStyle(
        "CodeText",
        parent=styles["Normal"],
        fontName="Courier",
        fontSize=8.2,
        leading=11,
        textColor=colors.HexColor("#2d1b4e"),
        wordWrap="CJK",
        splitLongWords=True,
        spaceAfter=0,
    )

    callout_style = ParagraphStyle(
        "CalloutText",
        parent=body_style,
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#581c87"),
        leftIndent=0,
    )

    return {
        "Title": title_style,
        "H1": h1_style,
        "H2": h2_style,
        "H3": h3_style,
        "Body": body_style,
        "Bullet": bullet_style,
        "Code": code_style,
        "Callout": callout_style,
    }


# ---------------------------------------------------------------------------
# Code helpers
# ---------------------------------------------------------------------------

def _escape_code_line(text: str) -> str:
    """Escape terminal text for ReportLab XML while preserving indentation."""

    text = (
        text
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )

    # Preserve leading spaces.
    leading = len(text) - len(text.lstrip(" "))

    if leading:
        text = (
            ("&#160;" * leading)
            + text[leading:]
        )

    return text


def _build_wrapped_code_table(
    code_text: str,
    styles: dict[str, ParagraphStyle],
) -> Table:
    """
    Build a code-output box that wraps long terminal lines
    without adding extra vertical spacing between lines.
    """

    raw_lines = code_text.split("\n")

    rows = []

    for line in raw_lines:

        if line == "":
            paragraph = Paragraph(
                "&#160;",
                styles["Code"],
            )
        else:
            escaped = _escape_code_line(line)

            paragraph = Paragraph(
                escaped,
                styles["Code"],
            )

        rows.append([paragraph])

    table_width = 540

    table = Table(
        rows,
        colWidths=[table_width],
        repeatRows=0,
        splitByRow=1,
        hAlign="LEFT",
    )

    # No vertical padding between individual lines.
    # Only the first and last rows get outer spacing.
    table.setStyle(
        TableStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, -1),
                    colors.HexColor("#faf5ff"),
                ),

                (
                    "BOX",
                    (0, 0),
                    (-1, -1),
                    2,
                    colors.HexColor("#c084fc"),
                ),

                (
                    "LEFTPADDING",
                    (0, 0),
                    (-1, -1),
                    12,
                ),

                (
                    "RIGHTPADDING",
                    (0, 0),
                    (-1, -1),
                    12,
                ),

                # Remove extra vertical space between lines.
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    0,
                ),

                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    0,
                ),

                # Small padding at the top of the box.
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, 0),
                    6,
                ),

                # Small padding at the bottom of the box.
                (
                    "BOTTOMPADDING",
                    (0, -1),
                    (-1, -1),
                    6,
                ),

                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "TOP",
                ),
            ]
        )
    )

    return table
# ---------------------------------------------------------------------------
# Markdown parser
# ---------------------------------------------------------------------------

def parse_markdown_to_flowables(
    md_content: str,
    styles: dict[str, ParagraphStyle],
) -> list:
    """Parse Markdown into ReportLab flowables."""

    flowables = []

    lines = md_content.splitlines()

    i = 0

    in_code_block = False
    code_lines = []
    code_lang = ""

    while i < len(lines):

        line = lines[i]

        # ---------------------------------------------------------------
        # Code block
        # ---------------------------------------------------------------

        if line.strip().startswith("```"):

            if not in_code_block:

                in_code_block = True

                code_lang = (
                    line.strip()
                    .lstrip("`")
                    .strip()
                )

                code_lines = []

            else:

                in_code_block = False

                code_text = "\n".join(
                    code_lines
                )

                if code_text:

                    flowables.append(
                        Spacer(
                            1,
                            6,
                        )
                    )

                    # ---------------------------------------------------
                    # FIX:
                    # Use wrapped table instead of Preformatted.
                    # ---------------------------------------------------

                    code_table = (
                        _build_wrapped_code_table(
                            code_text,
                            styles,
                        )
                    )

                    flowables.append(
                        code_table
                    )

                    flowables.append(
                        Spacer(
                            1,
                            10,
                        )
                    )

            i += 1
            continue

        if in_code_block:

            code_lines.append(line)

            i += 1
            continue

        stripped = line.strip()

        # ---------------------------------------------------------------
        # Empty line
        # ---------------------------------------------------------------

        if not stripped:

            i += 1
            continue

        # ---------------------------------------------------------------
        # Horizontal rule
        # ---------------------------------------------------------------

        if stripped in (
            "---",
            "***",
            "___",
        ):

            flowables.append(
                Spacer(
                    1,
                    6,
                )
            )

            flowables.append(
                HRFlowable(
                    width="100%",
                    thickness=1.5,
                    color=colors.HexColor("#e9d5ff"),
                    spaceBefore=8,
                    spaceAfter=12,
                )
            )

            i += 1
            continue

        # ---------------------------------------------------------------
        # H1
        # ---------------------------------------------------------------

        if stripped.startswith("# "):

            title_text = _clean_inline_markdown(
                stripped[2:]
            )

            flowables.append(
                Spacer(
                    1,
                    4,
                )
            )

            flowables.append(
                Paragraph(
                    title_text,
                    styles["Title"],
                )
            )

            flowables.append(
                Spacer(
                    1,
                    2,
                )
            )

            hr1 = HRFlowable(
                width="100%",
                thickness=3,
                color=colors.HexColor("#ec4899"),
                spaceBefore=0,
                spaceAfter=2,
            )

            hr2 = HRFlowable(
                width="100%",
                thickness=1.5,
                color=colors.HexColor("#c084fc"),
                spaceBefore=0,
                spaceAfter=12,
            )

            flowables.append(hr1)
            flowables.append(hr2)

            i += 1
            continue

        # ---------------------------------------------------------------
        # H2
        # ---------------------------------------------------------------

        elif stripped.startswith("## "):

            h2_text = _clean_inline_markdown(
                stripped[3:]
            )

            h2_html = _format_header_badges(
                h2_text
            )

            flowables.append(
                Spacer(
                    1,
                    2,
                )
            )

            flowables.append(
                Paragraph(
                    h2_html,
                    styles["H2"],
                )
            )

            flowables.append(
                Spacer(
                    1,
                    1,
                )
            )

            i += 1
            continue

        # ---------------------------------------------------------------
        # H3
        # ---------------------------------------------------------------

        elif stripped.startswith("### "):

            h3_text = _clean_inline_markdown(
                stripped[4:]
            )

            flowables.append(
                Paragraph(
                    h3_text,
                    styles["H3"],
                )
            )

            flowables.append(
                Spacer(
                    1,
                    1,
                )
            )

            i += 1
            continue

        # ---------------------------------------------------------------
        # Bullet list
        # ---------------------------------------------------------------

        if (
            stripped.startswith("- ")
            or stripped.startswith("* ")
        ):

            item_text = _clean_inline_markdown(
                stripped[2:]
            )

            flowables.append(
                Paragraph(
                    f"◆ {item_text}",
                    styles["Bullet"],
                )
            )

            i += 1
            continue

        # ---------------------------------------------------------------
        # Callout / Quote / Expected Output
        # ---------------------------------------------------------------

        if (
            stripped.startswith("*Expected Output:*")
            or stripped.startswith("> ")
        ):

            callout_text = (
                _clean_inline_markdown(
                    stripped.lstrip("> ").strip()
                )
            )

            paragraph = Paragraph(
                callout_text,
                styles["Callout"],
            )

            table = Table(
                [[paragraph]],
                colWidths=[540],
            )

            table.setStyle(
                TableStyle(
                    [
                        (
                            "BACKGROUND",
                            (0, 0),
                            (-1, -1),
                            colors.HexColor("#fce7f3"),
                        ),

                        (
                            "LINELEFT",
                            (0, 0),
                            (0, 0),
                            4,
                            colors.HexColor("#ec4899"),
                        ),

                        (
                            "LEFTPADDING",
                            (0, 0),
                            (-1, -1),
                            12,
                        ),

                        (
                            "RIGHTPADDING",
                            (0, 0),
                            (-1, -1),
                            12,
                        ),

                        (
                            "TOPPADDING",
                            (0, 0),
                            (-1, -1),
                            8,
                        ),

                        (
                            "BOTTOMPADDING",
                            (0, 0),
                            (-1, -1),
                            8,
                        ),
                    ]
                )
            )

            flowables.append(
                Spacer(
                    1,
                    6,
                )
            )

            flowables.append(table)

            flowables.append(
                Spacer(
                    1,
                    8,
                )
            )

            i += 1
            continue

        # ---------------------------------------------------------------
        # Normal paragraph
        # ---------------------------------------------------------------

        para_text = _clean_inline_markdown(
            stripped
        )

        flowables.append(
            Paragraph(
                para_text,
                styles["Body"],
            )
        )

        i += 1

    return flowables


# ---------------------------------------------------------------------------
# Markdown formatting
# ---------------------------------------------------------------------------

def _clean_inline_markdown(text: str) -> str:
    """Convert Markdown inline styles to ReportLab XML."""

    # Escape XML special characters first.
    text = (
        text
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )

    # Bold.
    text = re.sub(
        r"\*\*(.*?)\*\*",
        r'<b><font color="#7c3aed">\1</font></b>',
        text,
    )

    # Italic.
    text = re.sub(
        r"\*(.*?)\*",
        r'<i><font color="#a855f7">\1</font></i>',
        text,
    )

    # Inline code.
    text = re.sub(
        r"`(.*?)`",
        r'<font name="Courier" color="#6b21a8" size="9"><b>\1</b></font>',
        text,
    )

    return text


def _format_header_badges(
    text: str,
) -> str:
    """Format category tags like [SETUP], [CONFIG]."""

    badge_colors = {
        "SETUP": "#db2777",
        "DEPENDENCY": "#a855f7",
        "CONFIG": "#c084fc",
        "BUILD": "#f472b6",
        "EXECUTION": "#7c3aed",
        "VERIFICATION": "#ec4899",
        "CLEANUP": "#9370db",
    }

    def replace_badge(match):

        tag = match.group(1).upper()

        color = badge_colors.get(
            tag,
            "#a855f7",
        )

        return (
            f' <font color="{color}">'
            f'<b>[{tag}]</b>'
            f'</font>'
        )

    return re.sub(
        r"\[([A-Za-z0-9_-]+)\]",
        replace_badge,
        text,
    )


# ---------------------------------------------------------------------------
# PDF rendering
# ---------------------------------------------------------------------------

def render_markdown_to_pdf(
    md_content: str,
    output_path: Path,
    doc_title: str | None = None,
) -> Path:
    """Convert Markdown into a styled PDF document."""

    output_path = Path(
        output_path
    )

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=letter,
        leftMargin=36,
        rightMargin=36,
        topMargin=60,
        bottomMargin=60,
        allowSplitting=1,
    )

    styles = _build_styles()

    flowables = parse_markdown_to_flowables(
        md_content,
        styles,
    )

    doc.build(
        flowables,
        canvasmaker=FlowScopeCanvas,
    )

    return output_path


# ---------------------------------------------------------------------------
# File rendering
# ---------------------------------------------------------------------------

def render_pdf_file(
    input_path: Path,
    output_path: Path,
) -> Path:
    """Read Markdown or blocks JSON and convert it into a PDF."""

    input_path = Path(
        input_path
    )

    if not input_path.exists():

        raise FileNotFoundError(
            f"Input file not found: {input_path}"
        )

    content = input_path.read_text(
        encoding="utf-8"
    )

    # If input is blocks JSON, convert using
    # flowscope_markdown when available.
    if input_path.suffix == ".json":

        try:

            import flowscope_markdown

            content = (
                flowscope_markdown.render_markdown(
                    input_path
                )
            )

        except Exception:
            pass

    return render_markdown_to_pdf(
        content,
        output_path,
    )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:

    if len(sys.argv) < 2:

        sys.exit(
            f"Usage: {sys.argv[0]} "
            "<input.md|blocks.json> "
            "[--out output.pdf]"
        )

    input_path = Path(
        sys.argv[1]
    )

    out_path = input_path.with_suffix(
        ".pdf"
    )

    if (
        "--out" in sys.argv
        or "-o" in sys.argv
    ):

        idx = (
            sys.argv.index("--out")
            if "--out" in sys.argv
            else sys.argv.index("-o")
        )

        out_path = Path(
            sys.argv[idx + 1]
        )

    result = render_pdf_file(
        input_path,
        out_path,
    )

    print(
        f"PDF guide successfully generated at: {result}"
    )


if __name__ == "__main__":
    main()